version: "3.4"

services:
  app:
    build: .
    command: npm start
    env_file:
      - .env
    volumes:
      - node_modules:/opt/app/node_modules
      - .:/opt/app
    ports:
      - "3000:3000"
      - "35729:35729"

volumes:
  node_modules:
